name: 🚀 Deploy Laravel Project via FTP

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Specify the required PHP version
          extensions: mbstring, xml, bcmath, curl  # Add any required PHP extensions

      - name: Install Dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Create .env file
        run: |
          echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "DB_CONNECTION=mysql" >>